config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping_list.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_list/urls.py
from django.urls import path

from shopping_list import views

app_name = 'shopping_list'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('create_prod/', views.ProductCreateView.as_view(), name='create_prod'),
    path('update_prod/<int:pk>/', views.ProductUpdateView.as_view(), name='update_prod'),
    path('detail_prod/<int:pk>', views.ProductDetailView.as_view(), name='detail_prod'),
    path('delete_prod/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_prod'),
    path('category_list/<int:pk>', views.CategoryListView.as_view(), name='category_list'),
    path('create_cat/', views.CategoryCreateView.as_view(), name='create_cat'),
    path('delete_cat/<int:pk>/', views.CategoryDeleteView.as_view(), name='delete_cat'),
]

shopping_list/models.py
from django.db import models
from django.db.models import PROTECT

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='name')
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('create_at',)


class Product(models.Model):

    name = models.CharField(max_length=150, verbose_name='name')
    details = models.TextField()
    category = models.ForeignKey(to='Category', on_delete=PROTECT, related_name='products')
    img = models.ImageField(upload_to='product_img/', **NULLABLE)
    price = models.PositiveIntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    change_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('change_at',)

shopping_list/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView

from shopping_list.models import Product, Category


class ProductListView(ListView):
    model = Product
    template_name = 'shopping_list/category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sorting = self.request.GET.get('sorting', 'by_date')
        context['sorting'] = sorting
        context['title'] = 'all products'
        context['is_all_categories'] = True
        products = Product.objects.all()
        if sorting == 'by_date':
            context['products'] = products.order_by('change_at')
        elif sorting == 'by_price':
            context['products'] = products.order_by('price')
        return context


class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'title': 'product',
    }


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'details', 'category', 'img', 'price']
    success_url = reverse_lazy('shopping_list:product_list')
    extra_context = {
        'title': 'create product',
        'is_new_product': True,
    }


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'details', 'category', 'img', 'price']
    success_url = reverse_lazy('shopping_list:product_list')
    extra_context = {
        'title': 'update product',
    }


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopping_list:product_list')
    extra_context = {'title': 'delete product'}


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        sorting = self.request.GET.get('sorting', 'by_date')
        context['sorting'] = sorting
        category = Category.objects.get(pk=pk)
        context['category'] = category
        context['title'] = category.name
        products = Product.objects.filter(category=pk)
        if sorting == 'by_date':
            context['products'] = products.order_by('change_at')
        elif sorting == 'by_price':
            context['products'] = products.order_by('price')
        return context


class CategoryCreateView(CreateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('shopping_list:product_list')
    extra_context = {
        'title': 'create category',
        'is_new_category': True,
    }


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('shopping_list:product_list')
    extra_context = {'title': 'delete category'}

shopping_list/templates/shopping_list/category_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/confirm_delete.css' %}">
{% endblock %}

{% block content %}
<div class="delete-block">
    <form class="delete-form" method="post">
        {% csrf_token %}
        <p class="question">delete category "{{ category.name }}"?</p>
        <button class="delete-button" type="submit">confirm</button>
        <a class="cancel-button" href="{% url 'shopping_list:category_list' category.pk %}">cancel</a>
    </form>

    <img class="image-question" src="{% static 'img/question.svg' %}">
</div>
{% endblock %}

shopping_list/templates/shopping_list/category_form.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
<link rel="stylesheet" href="{% static 'css/category_form.css' %}">
{% endblock %}

{% block content %}
<div class="top-correction" style="margin-top:4em;"></div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="confirm-button" type="submit">confirm</button>
</form>

<a class="common-button" href="{% url 'shopping_list:product_list' %}">cancel</a>
{% endblock %}

shopping_list/templates/shopping_list/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/item_card.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
{% endblock %}

{% block sorting %}
    {% include 'shopping_list/includes/sorting.html' %}
{% endblock %}

{% block content %}
<div class="top-correction" style="margin-top:4em;"></div>

{% for object in products %}
    {% include 'shopping_list/includes/item_card.html' %}
{% endfor %}

<br>
{% if not is_all_categories %}
<a class="delete-button" href="{% url 'shopping_list:delete_cat' category.pk %}">delete category</a>
{% endif %}
<br>
<div class="top-correction" style="margin-top:4em;"></div>
{% endblock %}

shopping_list/templates/shopping_list/includes/item_card.html
{% load static %}

<div class="item-card">
    {% if object.img %}
        <img class="item-photo" src="{{ object.img.url }}">
    {% else %}
        <img class="item-photo" src="{% static 'img/default.svg' %}">
    {% endif %}
    <div class="info">
        <div class="item-name">{{ object.name }}</div>
        <div class="details">{{ object.details|truncatewords:7 }}</div>
        <div class="details">price: {{ object.price }}</div>
        <div class="details">date: {{ object.change_at }}</div>
    </div>
    <div class="item-buttons">
        <a class="common-button" href="{% url 'shopping_list:detail_prod' object.pk %}">show details</a>
    </div>
</div>

shopping_list/templates/shopping_list/includes/sorting.html
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/sorting.css' %}">
{% endblock %}

<div class="sorting">
    <div class="sorting-name">sorting:</div>
    {% if sorting %}
        {% if sorting == 'by_date' %}
            <div class="by-date active">by date</div>
            <a href="?sorting=by_price"><div class="by-price">by price</div></a>
        {% elif sorting == 'by_price' %}
            <a href="?sorting=by_date"><div class="by-date">by date</div></a>
            <div class="by-price active">by price</div>
        {% endif %}
    {% endif %}
</div>

shopping_list/templates/shopping_list/product_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/confirm_delete.css' %}">
{% endblock %}

{% block content %}
<div class="delete-block">
    <form class="delete-form" method="post">
        {% csrf_token %}
        <p class="question">delete product "{{ object.name }}"?</p>
        <button class="delete-button" type="submit">confirm</button>
        <a class="cancel-button" href="{% url 'shopping_list:detail_prod' object.pk %}">cancel</a>
    </form>
</div>
{% endblock %}

shopping_list/templates/shopping_list/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/product_detail.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
{% endblock %}

{% block content %}
<div class="top-correction" style="margin-top:4em;"></div>
<div class="product">
    {% if object.img %}
        <img class="item-img" src="{{ object.img.url }}">
    {% else %}
        <img class="item-img" src="{% static 'img/default.svg' %}">
    {% endif %}
    <div class="text">
        <div class="item-name">{{ object.name }}</div>
        <div class="item-details">{{ object.details }}</div>
        <div class="item-price">price: {{ object.price }}</div>
        <div class="update-date">{{ object.change_at }}</div>
    </div>
    <a class="common-button" href="{% url 'shopping_list:update_prod' object.pk %}">edit</a>
    <a class="delete-button" href="{% url 'shopping_list:delete_prod' object.pk %}">delete</a>
</div>

{% endblock %}

shopping_list/templates/shopping_list/product_form.html
{% extends 'base.html' %}
{% load categories_tags %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
<link rel="stylesheet" href="{% static 'css/product_form.css' %}">
<link rel="stylesheet" href="{% static 'css/category_form.css' %}">
{% endblock %}

{% block content %}
    <div class="top-correction" style="margin-top:4em;"></div>
    {% get_categories as categories %}
    {% if categories %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="confirm-button" type="submit">confirm</button>
        </form>

        <a class="common-button" href="{% url 'shopping_list:product_list' %}">cancel</a>
    {% else %}
        <div class="warning-message">First you need to create at least one category</div>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}
{% load categories_tags %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/null_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    <div class="base-field">
        <div class="left-bar">
            <img class="logo" src="{% static 'img/logo.svg' %}">
            <h1 class="page-title">{{ title|upper }}</h1>

            {% if is_all_categories %}
                <div class="current-section">all products</div>
            {% else %}
                <a class="section-button" href="{% url 'shopping_list:product_list' %}">all products</a>
            {% endif %}

            {% get_categories as categories %}
            {% for category in categories %}
                {% if category.name == title %}
                    <div class="current-section">{{ category.name }}</div>
                {% else %}
                    <a class="section-button" href="{% url 'shopping_list:category_list' category.pk %}">{{ category.name }}</a>
                {% endif %}
            {% endfor %}

            <br>
            <br>

            {% if is_new_category %}
                <div class="current-section">new category</div>
            {% else %}
                <a class="section-button" href="{% url 'shopping_list:create_cat' %}">new category</a>
            {% endif %}

            {% if is_new_product %}
                <div class="current-section">new product</div>
            {% else %}
                <a class="section-button" href="{% url 'shopping_list:create_prod' %}">new product</a>
            {% endif %}
        </div>

        <div class="main-field ">
            <div class="header">
                {% block sorting %}{% endblock %}
            </div>

            {% block content %}{% endblock %}

            <div class="footer">
                <div class="developer-contact">
                    <a href="https://t.me/elcapitansmetankins" target="_blank">
                        <img class="logo-telegram" src="{% static 'img/logo-telegram.svg' %}" alt="logo Telegram">
                    </a>
                    <a href="https://t.me/elcapitansmetankins" target="_blank">
                        <div class="developer-contact-text">developer contact</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>